---
# tasks file for nerd-fonts

- name: Ensure fonts directory is created
  become: true
  file:
    path: "{{ fonts_folder }}"
    state: directory

- name: Check if Hack Nerd Font exists
  become: true
  stat:
    path: "{{ fonts_folder }}/HackNerdFont-Regular.ttf"
  register: hack_font

- name: Download and extract Hack Nerd Font
  when: not hack_font.stat.exists
  become: true
  ansible.builtin.unarchive:
    src: "https://github.com/ryanoasis/nerd-fonts/releases/download/v{{ fonts_version }}/Hack.tar.xz"
    dest: "{{ fonts_folder }}"
    remote_src: true

- name: Check if FiraCode Nerd Font exists
  become: true
  stat:
    path: "{{ fonts_folder }}/FiraCodeNerdFont-Regular.ttf"
  register: fira_font

- name: Download and extract FiraCode Nerd Font
  when: not fira_font.stat.exists
  become: true
  ansible.builtin.unarchive:
    src: "https://github.com/ryanoasis/nerd-fonts/releases/download/v{{ fonts_version }}/FiraCode.tar.xz"
    dest: "{{ fonts_folder }}"
    remote_src: true

- name: Rebuild font cache
  become: true
  ansible.builtin.command: fc-cache -fv
  changed_when: false
